ooyala/html5-ad-plugins

- js/freewheel.js
- Issue was caused by a TypeError in the fw_onSlotStarted function
- Similar issue found in fw_onSlotEnded function
- Add check to prevent TypeError in the event that adVideoElement is null or if the ad is non-linear
> [PBI-1252] Fix issue where preroll overlay was being time out by AMC

- js/freewheel.js
In this.onReplay() within ad_manager_controller.js we call
_triggerAdManagerCallback(this.EVENTS.REPLAY_REQUESTED); which in turn
invokes the event listener for this event within the specific ad
manager (in this case freewheel ad manager). The event listener for
EVENTS.REPLAY_REQUESTED was missing in freewheel.js. Adding the event
listener onRePlayRequested fixed the issue. Appears to also solve
PBI-1259
> [PBW-3961][Chrome][FW] - PreMidPost - Looping after it replays

- js/google_ima.js
-When in single video element mode, IMA will now wait until content resume message from IMA before ending ad pod.
> [PBW-4052]

- js/freewheel.js
-fixed an issue where FW video ads would not play on mobile devices
-However, this also makes it overlay ads cannot be interacted with on iOS devices (mainly will affect iPad). We'll have to live with this for now until Freewheel provides us a way to do so
> [PBI-1459]

- js/ad_manager_vast.js
- test/unit-test-helpers/mock_responses/vast_linear_no_clickthrough.xml
- test/unit-tests/vast_test.js
-fixed an issue where it was possible to trigger a window.open leading to a blank page with a Vast ad without a clickthrough defined
-added a new mock xml to test for when there is no clickthrough defined for a linear ad
> [PBI-1484]

- js/ad_manager_vast.js
-fixed end of ad flow for VPAID 2.0 ads. We will wait for AD_STOPPED from creative before proceeding
-removed extra iframes when VPAID 2.0 ad finishes
-removed video restrictions for VAST ads
-renamed iframe to vpaidIframe for clarification
> Vast vpaid

- js/google_ima.js
-added a workaround to handle an issue that arises when the user clicks on “Done” on iPhone devices, leaving the native video player.
> [PBI-1599]

- js/ad_manager_vast.js
-fixed an issue where variables were out of order when calling initVpaidAd. We now properly follow the VPAID 2.0 spec
-fixed an issue where exceptions in creatives were not properly encapsulated by a try/catch in safeFunctionCall
-note that Francisco is currently working on unit tests but will not make the March build. The unit tests will test for these issues
> [PBI-1608]

- js/ad_manager_vast.js
-workaround of an issue on Mac Safari where VPAID 2.0 video creative midrolls get stuck buffering
> [PBI-1609]

- js/google_ima.js
- test/unit-tests/ima_test.js
-fixed an issue where we do not provide the correct shared video element on iOS to the IMA SDK when the original video element is destroyed and recreated
> [PBI-1666]

- js/freewheel.js
-Removed workaround to reposition overlays when video size changes. Freewheel has addressed this in their latest release, version 6.8
> [PBI-1721]

- js/google_ima.js
- test/unit-tests/ima_test.js
-reverted IMA overlay blink changes because of side effects. Will revisit in the future.
> [PBW-5838]

- js/pulse.js
Add the ability to pass callbacks, as page level parameters, which will receive internal session & ad player objects as they are created
> PSDK-527: Add optional callbacks for emitting session & ad player

- js/pulse.js
Don't call onSessionCreated until we get SESSION_STARTED from the ad player.
> PSDK-566: Better onSessionCreated

- js/google_ima.js
We are raising the timeout because VPAID 1.0 ads seem to take longer to load and this will hopefully eliminate some of the customer headache of losing revenue from ads failing to load in time.
> [raise-timeout] Raising IMA's ad requesting time-out to 5 seconds.

- js/google_ima.js
- test/unit-test-helpers/mock_amc.js
- test/unit-tests/ima_test.js
-fixed an issue where a linear video playing in single video element mode would not end the current ad pod when it finishes
-removed outdated comments
-fixed an issue in the ima unit tests where the amc was not a new object at the beginning of each test
> [PBW-5938]

- js/google_ima.js
Remove second -> millisecond conversion of AD_LOAD_TIMEOUT constant because it is already converted
> [PBI-1958]

- js/ad_manager_vast.js
- test/unit-tests/vast_test.js
-added back in ad tag url overrides from page level settings
Doc for reference: http://help.ooyala.com/video-platform/concepts/pbv4_ads_dev_vast_parameters.html
> [PBI-2015]

- js/google_ima.js
- test/unit-test-helpers/mock_ima.js
- test/unit-tests/ima_test.js
- only update play head on COMPLETE (IMA event) if the ad linear
> [PBI-2051] Fix issue where closing overlay ad resets playhead to 0

- js/google_ima.js
- test/unit-tests/ima_test.js
-added support for page level setting “showAdControls” to control whether or not the ad controls appear for IMA ads
> [player-58]

- js/pulse.js
@pilievOoyala @aeng7 Can you guys check if this is okay? What we do here is just check if the SDK is loaded or not when our placeholder preroll ad should play. If it's not we tell the AMC it's ended so the player can move on. Let me know if you don't think that's the correct way of doing it.
Thanks!
> PSDK-688 : stop the placeholder ad right away if the SDK is not loaded

- js/google_ima.js
- test/unit-test-helpers/mock_ima.js
- test/unit-tests/ima_test.js
-found during testing of PLAYER-397 for Chromepocalypse
-fixes an issue where ad errors from the AdsManager object were not being handled properly
> Ad error fix

- js/pulse.js
Additionally, allow enabling Pulse debug mode by passing `pulse_debug` parameter to ad manager.
> PSDK-762: Don't stop ad pod just because SDK doesn't load near-instantly

- js/pulse.js
This pull request is the first step in supporting overlays for V4 + Pulse. Its current limitation is that it will track impression as soon as we tell the player to show the overlay image. We'll add support for error tracking in a later release. This code also contains some commented code for the upcoming support of pause ads as well.
> PSDK 472: Overlay support for the Pulse plugin

- js/ad_manager_vast.js
- test/unit-tests/vast_test.js
-fixed an issue in the vast ad manager where wrapper ads would cause the ad pod to end early (before wrapper ads are processed). This caused a content flicker for preroll ads
> [PBI-2100]

- js/google_ima.js
- test/unit-test-helpers/mock_amc.js
- test/unit-test-helpers/mock_ima.js
- test/unit-tests/ima_test.js
[Ticket](https://jira.corp.ooyala.com/browse/PLAYER-319)
The cause of the issue was similar to what was described on the ticket. The IMA sdk was trying to initialize the overlay, but since the _AdDisplayContainer_ hadn't been set up yet, it bailed out with the following error:
_AdError 501: The overlay ad content could not be displayed since creative dimensions do not align with display area._
With these changes we get notified right before the ad is about to be displayed, so I'm using this cue to initialize the _AdDisplayContainer_. This also hooks up to the AMC so that the `Ad Impression` event gets fired. These changes also fix the exact same issue when using VMAP.
**Known issue:**
The IMA guys confirmed that there is a bug in the SDK that prevents the `COMPLETE` event from getting …
> [PLAYER-319] - (IMA) Added support for non-linear ads when using Ad Rules or VMAP

- js/pulse.js
This change is to allow the player to set the Pulse persistent ID so that it matches the device ID used in the video analytics SDK. This will allow us to get analytics on all the video and ad events for a given device.
> set persistent id to the player device id

- js/pulse.js
The presence of `_currentAd_` would cause overlay clickthrough to open the URL of the last played linear ad; fixed now
> Pulse plugin: clear _currentAd when ad playback ends

- js/google_ima.js
- test/unit-test-helpers/mock_amc.js
- test/unit-test-helpers/mock_ima.js
- test/unit-tests/ima_test.js
-fixed an issue where IMA ads can still load if the IMA plugin times out after sending out the ad request. This causes the player to go into a bad state
> Player 1033

- js/google_ima.js
- test/unit-test-helpers/mock_amc.js
- test/unit-test-helpers/mock_ima.js
- test/unit-tests/ima_test.js
-removed separate AD_BREAK_READY, CLICK, CONTENT_PAUSE_REQUESTED, and CONTENT_RESUME_REQUESTED listeners. These are handled in the _IMA_SDK_onAdEvent function now
-integrated with the new AMC onSdkAdEvent API
> Player 1256

- js/ad_manager_template.js
- js/pulse.js
Note that this is a suggestion and is not fully tested. Please feel free to make any changes necessary.
-fixed an issue where if there is no _pulseHost, the AMC has to wait until the Pulse ad plugin times out before notifying of playback ready
> [pulse-ready-fix]

- js/pulse.js
-added a check to return an empty timeline if it is determined there isn’t a Pulse configuration setup for the asset
> [pulse-timeline-fix]

- js/ad_manager_vast.js
- test/unit-test-helpers/mock_responses/vast_linear.xml
- test/unit-test-helpers/mock_responses/vast_overlay_missing_url.xml
- test/unit-test-helpers/mock_responses/vast_wrapper_1.xml
- test/unit-test-helpers/mock_responses/vast_wrapper_2.xml
- test/unit-test-helpers/mock_responses/vpaid_linear.xml
- test/unit-test-helpers/mock_vpaid.js
- test/unit-tests/vast_test.js
-fixed an issue where a wrapped VPAID ad would not have its parent wrapper tracking events fired
-fixed an issue where certain VPAID click tracking events were not fired
-fixed an issue where error trackers were not fired
-fixed an issue where clickThrough and customClick trackers were not fired
> Player 1394b

- js/google_ima.js
-removed an older workaround where we end the ad pod for live streams when we receive the COMPLETE event from IMA
> [pbw-6815]

- js/freewheel.js
- test/unit-test-helpers/mock_fw.js
- test/unit-tests/freewheel_test.js
_VIDEO_STATE_PLAYING_ needs to be set when the video resumes after being paused. I added the missing handler for this.
> [PBW-6889] Setting VIDEO_STATE_PLAYING when content is resumed

- js/google_ima.js
- test/unit-tests/ima_test.js
-workaround of an IMA issue where the ad starts paused on Safari 11 with our muted autoplay flow
-modified the setVolume function to set the volume as long as the IMA Ads Manager exists, and will toss the previous saved volume when doing so. This allows us to use this function to prime future ads for unmuted autoplay when called on a user click
> Player 1788b

- js/google_ima.js
- test/unit-tests/ima_test.js
-workarounds of two instances where IMA does not fire volume events
-fixed an issue where ads would start paused on mobile because IMA was not resuming when calling pause then resume immediately after
-making use of the new muteState argument since IMA does not separate mute states and volume
-adjusted the logic for saved volumes when muting/unmuting
> [player-1788]

- js/google_ima.js
-removed a workaround that is no longer needed for Google IMA where we had to pause and resume the ad immediately to start muted autoplayback. This was also causing an issue for podded ads on iOS
> [player-2136]

- js/google_ima.js
- test/unit-tests/ima_test.js
-we will always muted autoplay IMA starting from chrome 65 rather than 64
-fixed an issue where we attempt muted autoplay for an ad rules ad without a preroll
> [player-2426]

- js/google_ima.js
- test/unit-tests/ima_test.js
-fixed an issue where the IMA ad plugin flag for capturing a user click is reset when a content is autoplayed
> [player-2676]

- js/google_ima.js
- test/unit-tests/ima_test.js
-IMA will no longer notify of a volume change event when IMA mutes so that current player volume is not lost when IMA mutes
> [player-2810]

- js/freewheel.js
- test/unit-test-helpers/mock_fw.js
- test/unit-tests/freewheel_test.js
-workaround of an issue where FW unmutes after the first ad in an ad pod even though muted autoplay is required
> [player-3192]

- js/google_ima.js
- test/unit-tests/ima_test.js
-updated the Chrome version we check for when forcing muted autoplay for IMA
> [updateChromeAutoplayVersion]

- js/ad_manager_vast.js
- js/ssai_pulse.js
- test/test_lib.js
This fixes the issue in which the global jQuery object is either destroyed or modified by the Ad Manager Vast or SSAI Pulse plugins. The `InitOOJQuery` module from `html5-common` is not actually needed because ad plugins get their jQuery reference from the AMC. We will be deprecating `InitOOJQuery` since it causes conflicts with the global jQuery and it's only being used for unit test initialization.
> [PLAYER-2104] Removing unnecessary references to InitOOJQuery

- js/freewheel.js
- test/unit-tests/freewheel_test.js
[Ticket](https://jira.corp.ooyala.com/browse/PBW-7274)
Simple workaround for an issue in which the `event.slotCustomId` is being passed as `null` in some cases for Ad Impression events. Per Freewheel it seems that `adInstance.getSlot().getCustomId()` is the preferred way to access that value, so we're switching to that and using `event.slotCustomId` as a fallback only.
> [PBW-7274] Fix for event.slotCustomId being null in some cases

- js/freewheel.js
- test/unit-tests/freewheel_test.js
-fixed an issue where we are focusing the ad video element too late with Freewheel, causing video element sync issues between the video plugin and the Freewheel SDK
> [player-3601]

- js/ad_manager_vast.js
- test/unit-tests/vast_test.js
The cleanup of the non-linear ad wasn't being performed by the skin when the video was switched while the overlay was active.
> [PLAYER-3912] Notifying non-linear ad end when stream ends with active overlay

- gulpfile.js
- js/google_ima.js
- package.json
Setting the value of ads to 1 when it was already 1 was causing an error from Google IMA SDK. Fixed this.
Also added gulp webserver task for debugging purpose.
> [PBW-7596] prevented setting ads volume to 1 if it is already 1

- js/ooyala_ssai.js
- test/unit-tests/ooyala_ssai_test.js
SSAI backend requires current offset from the end. When video starts we should already know video duration to set it as offset.
`CONTENT_TREE_FETCHED` fires before start
> [PLAYER-5008] set current offset before start

- js/ad_manager_vast.js
We were doing ajax requests via jQuery before and violated the rule of how CORS should be done (preflight OPTIONS request never issued):
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
After migrating from jQuery.ajax to window.fetch preflight request started working and broke the frontend since backend responds 403 on it. Backend can't fix it. So we suppress OPTIONS request, despite it goes against CORS policy standards.
> fix/PLAYER-5363 suppressed CORS policy preflight request to get compatible with backend 403 response

- js/ad_manager_vast.js
window.fetch doesn't use XMLHttpRequest under the hood and proceeds CORS requests according to rules. Even after force doing CORS request in the last commit, the response text has been omitted (in network tab the response body can be seen, but it's not accessible in the code; empty string instead).
jQuery uses XMLHttpRequest and allows to overcome CORS limitation. This is why it was worked before and doesn't work now. Had to revert solution back to jQuery until backend team will fix the response.
> fix/PLAYER-5363 replaced window.fetch with jQuery.ajax temporarily

- js/google_ima.js
The issue was that ads were not displayed because DOM video element was not found in Safari and Chrome. Solution consist in modifying css selector to make it compatible with Safari.
> [PLAYER-5391] IMA ads play without ad video displayed

- js/ooyala_ssai.js
Fixing PLAER-5471 where ad controls are not showing up in Firefox and Safari for SSAI Ads.
On Firefox and Safari observed the below errors for both metadata and vast requests.Basically after the options call ,the GET call is failing with in browser.Basically even though Options is allowing all the headers with * but somehow FF is not allowing it.I removed cache-control and pragma headers from the request. From the error it is very clear that cache-control header needs to be removed .
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://ssai.ooyala.com/v1/metadata/dxbzNjZDE6nU5lB0PjWGQmD4Bqj9rcXZ?ssai_guid=be010e7b-a1de-4a2b-8257-f683bab567d1. (Reason: missing token ‘cache-control’ in CORS header ‘Access-Control-Allow-Headers’ from CORS …
> [PLAYER-5471] Fixing ad controls not showing up in FF and Safari

- js/google_ima.js
[related core PR](https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/676/overview)
First issue: 
when **video_controller** has created video element it calls *_notifyElementCreated* function
```javascript
_notifyElementCreated() {
const videoElement = element.parentContainer.find('#' + element.domId);
mb.publish(OO.EVENTS.VC_VIDEO_ELEMENT_CREATED, {
'parent': element.parentContainer,
'videoElement': videoElement,
});
}
```
in which it tries to find *videoElement* (or video wrapper as it's done with bitmovin) using element.**domId** which was previously passed to adManagerPlugins#create function (but can't do that because there's no element with such id in the DOM)
```javascript
const GoogleIMAVideoFactory = function() {
this.create = (parentContainer, id, …
```
> [PLAYER-5384] OSP bug

- js/ooyala_ssai.js
This branch add an extra validation in order to only process those request that get a successful response and be able to get Ad data.
> [PLAYER-5527] Validate response to only process successful requests 

- js/google_ima.js
For unknown reason in the asset with adPod in the middle one more adPod added on 0 position with 0 duration. Down by the code, this qualified as a failure and kills all the ad. I removed this artificial adPod launch (checking for duration greater than zero). Just initializing adManager and waiting for non-zero adPod.
> fix/PLAYER-5619 removed unnecessary run and stop of adTag of 0 duration

- js/google_ima.js
- test/unit-tests/ima_test.js
After several days of trying to fix the RC of this error, I couldn't find any acceptable way to fix it without breaking anything else. So I created a `div` and error `element.getElementsByTagName is not a function` wouldn't appear anymore.
> [PLAYER-5384] add div to avoid TypeError

- test/unit-tests/ima_test.js
I still have no idea, why empty adPod created here https://github.com/ooyala/html5-ad-plugins/blob/master/js/google_ima.js#L1994-L2002
But the truth is 0 duration ad shouldn't play. It's invalid, so I changed tests to the opposite expectations.
> PLAYER-5619 google_ima test changed. 0 duration ads shouldn`t play

- js/google_ima.js
Seems like the dep has been removed accidentally while linter was applied. Returned it back.
> fix/PLAYER-5670 jQuery dep handled properly
