js/ad_manager_template.js
js/ad_manager_vast.js
js/freewheel.js
js/google_ima.js
js/liverail.js

Support VTC in ad managers

---

js/google_ima.js

@gfrankOoyala Please review. Thanks! These changes are based on yesterday's email.

[PBI-672] Add companion ads to GoolgeIMA

---

js/google_ima.js

Add validation for pageSettings when checking for companionAds

---

js/google_ima.js

-Updated IMA-VTC plugin to include features and technology.
-IMA plugin will not validate correctly without these

Updating IMA plugin with new fields

---

js/ad_manager_template.js
js/freewheel.js
js/google_ima.js
test/unit-test-helpers/mock_ima.js
test/unit-tests/ima_test.js

This should be merged at the same time as the changes to html5-video-plugins (https://github.com/ooyala/html5-video-plugins/pull/55) and the core player (PR 464 open in mjolnir)

[PBW-3665] Support VTC+iOS+IMA

---

js/freewheel.js

- Adds a timeout to check if there is a response for the ad list request
- Raises error if there is no response

[PBI-731] Implement a timeout for fw_onAdRequestComplete event

---

js/freewheel.js

- should only set callback if not in testmode. oops

[PBI-731] Unbreak unit tests

---

js/freewheel.js

Associated with:
https://github.com/ooyala/html5-video-plugins/pull/96
https://github.com/ooyala/html5-common/pull/20
And two internal pull requests

[PBW-2677] Correct FW restrictions to plugins that support sharing give

---

js/google_ima.js
test/unit-tests/freewheel_test.js
test/unit-tests/ima_test.js

IMA:
-Fixed an issue where overlay would get cancelled preemptively

[PBW-4106]

---

js/ad_manager_vast.js
test/unit-tests/vast_test.js

- Add function, _hasLinearAd() to check if the ad has a linear ad before calling _handleLinearAd()
- Add function, _hasNonLinearAd() to check if the ad has a linear ad before calling _handleNonLinearAd()
- Code Cleanup and JSDoc fix

[PBI-1454] Fix error reporting issue and cleanup

---

js/freewheel.js

Unsubscribe to fw_adRequestComplete to properly timeout ad request

[PBI-731a]

---

js/google_ima.js
test/unit-test-helpers/mock_amc.js
test/unit-tests/ima_test.js

IMA
-IMA will now request the AMC to hide the player UI so that IMA UI elements are not blocked

[PBI-1479]

---

js/google_ima.js
test/unit-test-helpers/mock_ima.js

IMA
-added VPAID support
-removed usage of AUTO_SCALE since IMA VPAID does not currently seem to support it. We will grab the size from the uiContainer
-fixed an issue where IMA expected the AD_LOAD_TIMEOUT setting to be in milliseconds rather than seconds

[PBI-1503]

---

js/google_ima.js
test/unit-tests/ima_test.js

-fixed an issue where IMA was notifying AMC of a video ad play event for non linear ads

[PBI-1532]

---

js/ad_manager_vpaid.js

Please review. Missing unit tests.

Vpaid ad manager

---

js/ad_manager_vast.js
js/google_ima.js

-Workaround of a size change notification issue so that IMA ads and VPAID 2.0 standalone ads resize properly

[PBI-1597]

---

js/google_ima.js
test/unit-tests/ima_test.js

-We will set the ad manager to ready when both the ad display container is ready and if the metadata has been received
-We no longer will destroy the IMA ad plugin when VTC destroys the IMA-VTC plugin

[PBI-1635]

---

js/ad_manager_vast.js
test/unit-test-helpers/mock_responses/vast_linear_2_ads.xml
test/unit-tests/vast_test.js

-fixed an issue where Vast 2.0 tags with multiple ads would not have all their ads honored for playback

[PBI-1523]

---

js/ad_manager_vast.js
test/unit-test-helpers/mock_amc.js
test/unit-test-helpers/mock_responses/vpaid_linear.xml
test/unit-test-helpers/mock_responses/vpaid_linear_nocompanions.xml
test/unit-test-helpers/mock_responses/vpaid_linear_novalues.xml
test/unit-test-helpers/mock_responses/vpaid_nonlinear.xml
test/unit-test-helpers/mock_vpaid.js
test/unit-tests/vast_test.js

Please review :shipit:  I was adding some repeated tests for vast, until I realized it wasn't required, so only added vpaid specific stuff to the tests.

[PBI-1636] Add unit tests for vpaid

---

js/ad_manager_vast.js
js/google_ima.js

-removed 500 ms timeouts when handling size changes. mjolnir is improving its size changed notification so this is no longer needed

[PBI-1540]

---

js/ad_manager_vast.js

The vast ad manager had some strange spacing issues in the file.

-fixes improper spacing in the vast ad manager file

---

js/ad_manager_vast.js

Delete old proxy url code and fail ad immediately if there is a vast error

[PBI-1498]

---

js/ad_manager_vast.js
test/unit-test-helpers/mock_amc.js
test/unit-test-helpers/mock_responses/vast_linear.xml
test/unit-test-helpers/mock_responses/vast_overlay.xml
test/unit-tests/vast_test.js

- Supports the following tracking events: impression, creativeView, start, firstQuartile, midpoint, thirdQuartile, complete, mute, unmute, pause, resume, fullscreen, exitFullscreen, skip, close, ClickTracking, NonLinearClickTracing

[PBI-746] Ping tracking event urls

---

js/google_ima.js

-expose a page level parameter to allow people to request the INSECURE vpaid mode in the IMA ad manager

[pbi-1743]

---

js/google_ima.js
test/unit-tests/ima_test.js

IMA:
-fixed an issue where the ad id was not properly sent out when notifying of a  linear ad end

[PBI-1769]

---

js/freewheel.js
test/unit-test-helpers/mock_fw.js
test/unit-tests/freewheel_test.js

Freewheel:
-implemented parsing of external id

[PBI-1817]

---

js/ssai_pulse.js
test/unit-tests/ssai_pulse_test.js

- Add replaying of cached ad
- Fix issue caused by unbounded private functions
- Change code style

[PBI-1824a]

---

js/ssai_pulse.js
test/unit-tests/ssai_pulse_test.js

- this.currentAd.id3AdId was undefined

[PBI-1824b] Fix error in caching logic

---

js/google_ima.js

-introduced a page level setting to control the zIndex of the IMA iframe

[PBI-1833]

---

js/ssai_pulse.js
test/unit-test-helpers/mock_responses/ssai.xml
test/unit-tests/ssai_pulse_test.js
utils/VastParser.js

- supports "start", complete", "firstQuartile", "midpoint", "thirdQuartile", impression, and linear clickthrough tracking events

[PBI-1824c] Add tracking event support

---

js/google_ima.js

Added adsPlayed placeholder public method

[PBW-4530] After skipping a postroll, control bar on end screen show position of ad when it was skipped

---

js/ssai_pulse.js
test/unit-test-helpers/mock_responses/ssai.xml
test/unit-tests/ssai_pulse_test.js

- Add player configuration parameter: "cacheBuster". Default true. Only
an explicit value of "false" will turn off cacheBuster functionality
- Add function to replace CACHEBUSTING macro in tracking urls before pinging

[PBI-1847]

---

js/pulse.js

This allows jsdocs to parse correctly.

Added array as return value.

---

js/google_ima.js
test/unit-tests/ima_test.js

-fixed an issue where the video would flash black first prior to rendering an IMA overlay

[PBI-1927]

---

js/google_ima.js

-added page level setting to use Google’s countdown UI

[ima_countdown]

---

js/pulse.js

-changed encoding type from IMA to PULSE

[PSDK-542]

---

js/pulse.js

-changed AD_REQUEST ADTYPE to UNKNOWN_AD_REQUEST ADTYPE so that the ad video element gets created

[PBI-1995]

---

test/unit-test-helpers/mock_responses/ssai.xml
utils/vast_parser.js

Add missing Vast Parser function that is called when companion ads are available

[PLAYER-59]

---

js/google_ima.js
test/unit-tests/ima_test.js

-raising the DEFAULT_ADS_REQUEST_TIME_OUT to 15 seconds

[raise-timeout]

---

js/pulse.js

and don't enable Pulse SDK debug output 100% of the time

PSDK-762: Apply code review suggestions

---

js/pulse.js

- Only add pause insertion point filter if filter is already present.

PSDK-840: Fix ad playback

---

js/google_ima.js
test/unit-tests/ima_test.js

-fixed an issue where the IMA ad plugin and video plugin consume IMA pause and resume events after receiving an IMA ad complete event. This would throw the player into a bad state

[PLAYER-1038]

---

js/pulse.js

-fixed an issue where the content could not complete if the Pulse ad plugin was included with no Pulse ads

[player-1313]

---

js/ad_manager_vast.js
test/unit-tests/vast_test.js

-fixed an issue where VPAID ads in the Vast Ad Manager would not send out impressions

[player-1394]

---

js/google_ima.js
test/unit-test-helpers/mock_ima.js
test/unit-tests/ima_test.js

IMA
-setting a default loadVideoTimeout of 15 seconds
-removed a redundant unit test

[player-1374a]

---

js/google_ima.js
test/unit-test-helpers/mock_ima.js
test/unit-tests/ima_test.js

-muted autoplay functionality for IMA (Vast is handled via VTC)

[player-1788]

---

js/google_ima.js
test/unit-tests/ima_test.js

-update html5-common submodule
-IMA will now notify VTC of MUTE_STATE_CHANGE events
-updated unit tests for the new MUTE_STATE_CHANGE notification

[player-1897]

---

js/ad_manager_vast.js
js/freewheel.js
js/google_ima.js
js/liverail.js
js/pulse.js
js/ssai_pulse.js
test/unit-test-helpers/mock_amc.js
test/unit-tests/freewheel_test.js
test/unit-tests/ima_test.js
test/unit-tests/ssai_pulse_test.js
test/unit-tests/vast_test.js

PR to update ad plugins to create plugin loaded events for QoS

send plugin load events for pulse, freewheel, and ima

---

js/freewheel.js
test/unit-tests/freewheel_test.js

-fixed an issue where the video element was not ready for freewheel on mobile devices due to recent changes on ad video creation

[player-2137]

---

js/ad_manager_template.js
js/google_ima.js
test/unit-test-helpers/mock_ima.js
test/unit-tests/ima_test.js

Muted autoplay workarounds since IMA does not provide the proper hooks to handle muted autoplay

Player 2194 alt

---

js/google_ima.js
test/unit-test-helpers/mock_ima.js
test/unit-tests/ima_test.js

-IMA ad plugin will now report to the IMA SDK if we are intending to playback an ad muted

[player-2621]

---

js/ssai_pulse.js
test/unit-tests/ssai_pulse_test.js

https://jira.corp.ooyala.com/browse/PLAYER-2914

[PLAYER-2914] - SSAI Web Plugin

---

js/ad_manager_vast.js
js/freewheel.js
js/google_ima.js
test/unit-test-helpers/mock_amc.js
test/unit-test-helpers/mock_ima.js
test/unit-tests/freewheel_test.js
test/unit-tests/ima_test.js
test/unit-tests/vast_test.js

Player 2103

---

js/google_ima.js
test/unit-tests/ima_test.js

-fixed an issue where we are focusing the ad video element too late in environments where we’re allowed only a single video element
-workaround of an issue where the IMA iframe blocks clicks to our UI

[player-3603]

---

js/google_ima.js

-IMA iframe workaround will apply before showing ads now

[player-3600]

---

js/ooyala_ssai.js
test/unit-tests/ooyala_ssai_test.js

https://jira.corp.ooyala.com/browse/PLAYER-3539

[PLAYER-3539] Rename Ooyala Player SSAI plugin

---

js/ooyala_ssai.js
test/unit-tests/ooyala_ssai_test.js

Implementing ad pause/resume methods to clear ad timeout and make ui ad controls to disappear in the right time.

[PLAYER-3418] Expected UI Controls during SSAI Ad Playback

---

js/google_ima.js

There is no unit test because this section of code is only run when we are setting up the Google SDK and we don't download that for unit tests.

Player 3519

---

js/ssai_heartbeat.js

[PLAYER-2911]

---

js/pulse.js

Updates the Pulse ad manager to allow for muted autoplay.
Note there are no unit tests for the Pulse ad plugin.

Pulse autoplay changes

---

js/ooyala_ssai.js
utils/vast_parser.js

Rename global jQuery for Ooyala internal jQuery reference

[PLAYER-4414] Avoid use global jQuery reference at vast parser

---

js/google_ima.js
test/unit-test-helpers/mock_ima.js
test/unit-tests/ima_test.js

I'll add unit tests in the near future. This is to get QA started on testing these changes.

Player 1340 - Enable preloading of IMA ads

---

js/google_ima.js
test/unit-test-helpers/mock_amc.js
test/unit-test-helpers/mock_ima.js
test/unit-tests/ima_test.js

Also renamed playImaAd to tryPlayImaAd for clarity.

Player 1340 tests - Preloading ads unit tests

---

js/google_ima.js
test/unit-tests/ima_test.js

-fixed an issue where IMA was not showing the skip ad button for ad rules ads

[player-4770] - Skip Ad button is not shown for ad rules ads

---

js/ooyala_ssai.js

Added listener for PLAY_STARTED 
https://jira.corp.ooyala.com/browse/PLAYER-4232

Added listener for PLAY_STARTED

---

js/google_ima.js
test/unit-tests/ima_test.js

Hardcore value for "buffer" was changed from 0 to 1 to prevent showing a spinner on Ad screen.

[bugfix/PLAYER-5272]  loading spinner is displayed on IMA ads

---

package.json

Added package.json commands (dummy for now) to unblock devops

chore/PLAYER-4987 added package.json commands (dummy for now) to unblock devops

---

Jenkinsfile
sonar-project.properties

Added Jenkinsfile
Added sonar-project.propert

Player 5251

---

js/ooyala_ssai.js

The paused ads can be on pause longer than DVR can keep. This was not considered previously. Fixed it. Now for such a case, resume of the ads leading to immediate stopping the ads (removing ad controls as well).

[PLAYER-5500] added the logic when paused ads getting away from DVR

---

js/google_ima.js

Reverts ooyala/html5-ad-plugins#307

Revert "[PLAYER-5384] OSP bug"

---

js/google_ima.js
package-lock.json
test/unit-tests/ima_test.js
test/unit-tests/vast_test.js

The player was responding on invalid ad tag by the hanging black screen. This is because the ads weren't resetting in this case. Added reset.

[PBW-7945]

---

js/google_ima.js
package-lock.json
test/unit-tests/ima_test.js
test/unit-tests/vast_test.js

It remains unclear why rolling this PR back fixed the PLAYER-5600. Locally the issue doesn't reproduce. Creating this PR again to send it on QA for testing.

[PBW-7945] reset ad state for invalid ads

---

js/google_ima.js

Reverts ooyala/html5-ad-plugins#323

Revert "fix/PLAYER-5619 removed unnecessary run and stop of adTag of 0 duration"

---

js/google_ima.js

[PBW-5619] returned back duration check (reverted recently by accident)

---

js/google_ima.js
test/unit-tests/ima_test.js

Tests also was broken due to absence of globally defined jQuery. Fixed this.

[PLAYER-5670] tests fixed

---

js/google_ima.js
package-lock.json

Reverts ooyala/html5-ad-plugins#316

Revert "[PBW-7945] reset ad state for invalid ads"

---

js/google_ima.js
test/unit-tests/ima_test.js

This branch allow to mute the ad player if the user chooses to mute the first play attempt

[PBW-45502] Player overwriting ad tag parameter
